version: 1.7.0.{build}
configuration: Release
skip_tags: true

image: Visual Studio 2017

install:
  dotnet restore

build_script:
  dotnet build Saule.sln

test_script:
  - dotnet test Saule.Common.Tests
  - dotnet test Saule.AspNet.Tests
  - dotnet test Saule.AspNetCore.Tests

deploy:
- provider: NuGet
  api_key:
    secure: dtP6YFOY3quvyRlH0DYG/i4AbOegM/5oT8Q+IcpKMqKZgBiAmm+XRs2TN9+ju9oe
  on:
    appveyor_repo_tag: false
    branch: /(master|release-v.+)/
- release: saule-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: 00qfkOL3Upz61CDrcEkLV+Vnn2gY4zypijGU3oUXeyxI8pNYElkLMJGzgSOEcVnH
  artifact: /.*\.nupkg/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: false
    branch: /release-v.+/
